name: hobbybase
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.1

  firebase_analytics: ^5.0.11
  firebase_auth: 0.15.3

  google_sign_in: ^4.0.0
  firebase_dynamic_links: ^0.3.0
  cloud_firestore: ^0.13.4+2
  uuid: ^2.0.2

  fab_circular_menu: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  awesome_dialog: ^0.1.3
  imagebutton: ^0.0.6

dependency_overrides:
  firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/json/re100.json
    - assets/dq/dq01.png
    - assets/dq/dq02.png
    - assets/dq/dq03.png
    - assets/dq/dq04.png
    - assets/dq/dq05.png
    - assets/dq/dq06.png
    - assets/dq/dq07.png
    - assets/dq/dq08.png
    - assets/dq/dq09.png
    - assets/dq/dq10.png
    - assets/dq/dq11.png
    - assets/dq/dq12.png
    - assets/dq/dq13.png
    - assets/dq/dq14.png
    - assets/dq/dq15.png
    - assets/dq/dq16.png
    - assets/dq/dq17.png
    - assets/dq/dq18.png
    - assets/dq/dq19.png
    - assets/dq/dq20.png
    - assets/dq/dq21.png
    - assets/dq/dq22.png
    - assets/dq/dq23.png
    - assets/dq/dq24.png
    - assets/dq/dq25.png
    - assets/dq/dq26.png
    - assets/dq/dq27.png
    - assets/dq/dq28.png
    - assets/dq/dq29.png
    - assets/dq/dq30.png
    - assets/dq/dq31.png
    - assets/dq/dq32.png
    - assets/dq/dq33.png
    - assets/dq/dq34.png
    - assets/dq/dq35.png
    - assets/dq/dq36.png
    - assets/dq/dq37.png
    - assets/dq/dq38.png
    - assets/dq/dq39.png
    - assets/dq/dq40.png
    - assets/dq/dq41.png
    - assets/dq/dq42.png
    - assets/dq/dq43.png
    - assets/dq/dq44.png
    - assets/dq/dq45.png
    - assets/dq/dq46.png
    - assets/dq/dq47.png
    - assets/dq/dq48.png
    - assets/dq/dq49.png
    - assets/dq/dq50.png
    - assets/dq/dq51.png
    - assets/dq/dq52.png
    - assets/dq/dq53.png
    - assets/dq/dq54.png
    - assets/dq/dq55.png
    - assets/dq/dq56.png
    - assets/dq/dq57.png
    - assets/dq/dq58.png
    - assets/dq/dq59.png
    - assets/dq/dq60.png
    - assets/dq/dq61.png
    - assets/dq/dq62.png
    - assets/dq/dq63.png
    - assets/dq/dq64.png
    - assets/dq/dq65.png
    - assets/dq/dq66.png
    - assets/dq/dq67.png
    - assets/dq/dq68.png
    - assets/dq/dq69.png
    - assets/dq/dq70.png
    - assets/dq/dq71.png
    - assets/dq/dq72.png
    - assets/dq/dq73.png
    - assets/dq/dq74.png
    - assets/dq/dq75.png
    - assets/dq/dq76.png
    - assets/dq/dq77.png
    - assets/dq/dq78.png
    - assets/dq/dq79.png
    - assets/dq/dq80.png
    - assets/dq/dq81.png
    - assets/dq/dq82.png
    - assets/gunpla_grade/ic_highgrade_96.png
    - assets/gunpla_grade/ic_mastergrade_96.png
    - assets/gunpla_grade/ic_megasize_96.png
    - assets/gunpla_grade/ic_perfectgrade_96.png
    - assets/gunpla_grade/ic_re100_96.png
    - assets/gunpla_grade/ic_realgrade_96.png
    - assets/gunpla_grade/ic_sd_96.png
    - assets/gunpla/re100/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
